version: "3.8"
services:
  elasticsearch:
    mem_limit: 1G
    mem_reservation: 256M
    cpus: 0.8
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch

    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms448m -Xmx448m"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - thread_pool.write.queue_size=500
      - thread_pool.search.queue_size=1000

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    cap_add:
      - IPC_LOCK

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    ports:
      - "9200:9200"
      - "9300:9300"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

    logging:
      options:
        max-size: "100m"
        max-file: "5"

  fastapi:
    build: .
    container_name: fastapi
    mem_limit: 512M
    cpus: 0.7
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    restart: unless-stopped
    environment:
      - PANGO_ES_URL=http://elasticsearch:9200
      - PANGO_ANNOTATIONS_INDEX=${PANGO_ANNOTATIONS_INDEX}
      - PANGO_GENES_INDEX=${PANGO_GENES_INDEX}
      - HOST_URL=${HOST_URL}
      - HOST_PORT=${HOST_PORT}

volumes:
  elasticsearch-data:
    driver: local
